credentials:
  usernames:
    sagar:
      email: "sgrkamble0@gmail.com"
      name: "Dr. Sagar D. Kamble"
      password: "$2y$10$WaZmU7z5GQl/DHD4q7oZU.bUPU3uhhPZ18v92Yq1.7I.DQck7xqne"  # hashed  password

cookie:
  expiry_days: 30
  key: "random_signature_key"  # can be any random string
  name: "llm_assistant_cookie"

pre_authorization:
  emails:
    - "sgrkamble0@gmail.com"
